name: gourmet_go
description: "Build your ramen empire from a tiny eatery to a bustling restaurant! Snap every bowl you eat across Japan to unlock authentic regional styles, level up your chefs, and serve hungry customers in this dreamy pixel art sim."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.0
  hooks_riverpod: ^3.0.0

  # Camera & media
  camera: ^0.10.0
  image_picker: ^1.0.0
  video_player: ^2.8.0

  # 3D model viewer
  flutter_3d_controller: ^2.0.2

  # State management
  flutter_riverpod: ^3.3.1

  # Flame game engine ecosystem
  flame: ^1.36.0
  flame_audio: ^2.12.0
  flame_svg: ^1.12.0
  flame_behaviors: ^1.3.4
  flame_riverpod: ^5.5.3
  flame_splash_screen: ^0.3.1+3
  flame_jenny: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flame_test: ^2.2.3
  flame_lint: ^1.4.3
  riverpod_lint: ^3.1.3
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/models/
    - assets/audio/
    - assets/videos/
    - assets/sprites/
    - lib/fixtures/
