import 'dart:convert';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flame/flame.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:http/http.dart' as http;

import 'debug_logger.dart';

/// Loads pre-generated sprites from `assets/sprites/` and falls back to
/// Gemini runtime generation when a sprite is missing.
///
/// All FTUE sprites are pre-baked — the Gemini fallback is only for
/// runtime-generated assets (shop backgrounds, on-demand ramen bowls).
///
/// Sprite paths reference files generated by `scripts/generate_game_sprites.py`
/// and deployed to `assets/sprites/`.
class GameAssetService {
  static final GameAssetService _instance = GameAssetService._();
  factory GameAssetService() => _instance;
  GameAssetService._();

  static final _log = DebugLogger.instance;

  final _cache = <String, Uint8List>{};

  static const String _baseUrl =
      'https://generativelanguage.googleapis.com/v1beta';
  static const String _model = 'gemini-2.0-flash-preview-image-generation';

  static const String _styleGuide =
      'Dreamy anime-inspired aesthetic, soft pastel colour palette, '
      'warm golden lighting, gentle atmosphere, Studio Ghibli influence. '
      'Modern indie game aesthetic — fun and expressive without being childish. '
      'Warm rich colour palette. No text, no watermarks.';

  String get _apiKey => dotenv.env['GEMINI_API_KEY'] ?? '';

  // ── Pre-baked sprite paths ────────────────────────────────────────────────

  // Sous chef portraits
  static const sousChefNeutral = 'sprites/sous_chef_neutral.png';
  static const sousChefExcited = 'sprites/sous_chef_excited.png';
  static const sousChefThinking = 'sprites/sous_chef_thinking.png';

  // Kitchen background
  static const kitchenBg = 'sprites/kitchen_bg.png';

  // Speech bubble
  static const speechBubble = 'sprites/speech_bubble.png';

  // Bowl sprites by broth type
  static const bowlTonkotsu = 'sprites/bowl_tonkotsu.png';
  static const bowlShoyu = 'sprites/bowl_shoyu.png';
  static const bowlMiso = 'sprites/bowl_miso.png';
  static const bowlShio = 'sprites/bowl_shio.png';

  // Chef sprites (red = Ken, default chef)
  static const chefIdleRed = 'sprites/chef_idle_red.png';
  static const chefCooking01Red = 'sprites/chef_cooking_01_red.png';
  static const chefCooking02Red = 'sprites/chef_cooking_02_red.png';
  static const chefCooking03Red = 'sprites/chef_cooking_03_red.png';
  static const chefPlatingRed = 'sprites/chef_plating_red.png';
  static const chefCookingSheetRed = 'sprites/spritesheet_chef_cooking_red.png';

  /// Get the sous chef portrait path for a given mood.
  static String sousChefPortrait(SousChefMood mood) => switch (mood) {
        SousChefMood.neutral => sousChefNeutral,
        SousChefMood.excited => sousChefExcited,
        SousChefMood.thinking => sousChefThinking,
      };

  /// Get the bowl sprite path for a given broth type.
  static String bowlSprite(String brothBase) =>
      switch (brothBase.toLowerCase()) {
        'tonkotsu' => bowlTonkotsu,
        'shoyu' => bowlShoyu,
        'miso' => bowlMiso,
        'shio' => bowlShio,
        _ => bowlTonkotsu,
      };

  /// Get a customer sprite path.
  static String customerSprite(int index, CustomerState state) {
    final idx = (index % 6) + 1;
    final suffix = switch (state) {
      CustomerState.waiting => 'waiting',
      CustomerState.served => 'served',
      CustomerState.unhappy => 'unhappy',
    };
    return 'sprites/customer_${idx.toString().padLeft(2, '0')}_$suffix.png';
  }

  /// Get chef sprite path by colour variant.
  static String chefSprite(String colour, String pose) =>
      'sprites/chef_${pose}_$colour.png';

  // ── Asset loading ─────────────────────────────────────────────────────────

  /// Load a pre-baked sprite as raw bytes. Returns cached if available.
  Future<Uint8List?> loadSprite(String assetPath) async {
    final key = 'sprite:$assetPath';
    if (_cache.containsKey(key)) return _cache[key];

    try {
      final data = await rootBundle.load('assets/$assetPath');
      final bytes = data.buffer.asUint8List();
      _cache[key] = bytes;
      _log.logSuccess('GameAsset', 'loadSprite', '$assetPath (${bytes.length}B)');
      return bytes;
    } catch (e) {
      _log.logError('GameAsset', 'loadSprite', '$assetPath: $e');
      return null;
    }
  }

  /// Load a Flame [Image] from a sprite path.
  ///
  /// Uses Flame's image cache. The [assetPath] is relative to `assets/`.
  Future<ui.Image?> loadFlameImage(String assetPath) async {
    try {
      return await Flame.images.load(assetPath);
    } catch (e) {
      _log.logError('GameAsset', 'loadFlameImage', '$assetPath: $e');
      return null;
    }
  }

  /// Preload all FTUE-critical sprites into Flame's image cache.
  ///
  /// Call this during app startup to avoid load hitches during the FTUE.
  Future<void> preloadFtueAssets() async {
    final assets = [
      kitchenBg,
      sousChefNeutral,
      sousChefExcited,
      sousChefThinking,
      speechBubble,
      bowlTonkotsu,
      bowlShoyu,
      bowlMiso,
      bowlShio,
      chefIdleRed,
    ];

    for (final path in assets) {
      try {
        await Flame.images.load(path);
      } catch (e) {
        _log.logError('GameAsset', 'preload', '$path: $e');
      }
    }
    _log.logSuccess('GameAsset', 'preloadFtueAssets', '${assets.length} loaded');
  }

  // ── Runtime generation (Gemini fallback) ──────────────────────────────────

  Future<Uint8List?> getChefSprite() => _generate(
        'chef_sprite',
        'Cartoon chef character sprite, full body, front-facing, chibi proportions. '
        'Round friendly face with big expressive eyes and a warm smile. '
        'Modern white chef coat with bright orange piping and buttons, tilted white toque hat. '
        'Short stubby arms and legs, neutral happy walking pose. '
        'Isolated on solid bright green #00FF00 background for chroma key. '
        '$_styleGuide',
      );

  Future<Uint8List?> getChefPortrait() => _generate(
        'chef_portrait',
        'Close-up bust portrait of a cartoon chef guide character. '
        'Round friendly face, large warm expressive eyes, enthusiastic raised-eyebrow expression. '
        'Modern white chef coat with orange trim, tilted white toque. '
        'Warm rim lighting, slight vignette. Good for visual novel dialogue panel. '
        '$_styleGuide',
      );

  Future<Uint8List?> getRamenBowl(String regionId) {
    final (label, details) = _ramenDetails(regionId);
    return _generate(
      'ramen_bowl_$regionId',
      'Game item icon: a steaming bowl of $label. '
      '$details '
      'Viewed from slightly above at isometric angle, two wispy steam curls rising. '
      'White or transparent background, no scene context, icon-style composition. '
      '$_styleGuide',
    );
  }

  Future<Uint8List?> getShopBackground(String regionId) {
    final desc = _shopDesc(regionId);
    return _generate(
      'shop_bg_$regionId',
      'Interior background art for a ramen restaurant, wide landscape format. '
      '$desc '
      'No characters or people visible. Warm inviting light. No text, no readable signs. '
      '$_styleGuide',
    );
  }

  (String, String) _ramenDetails(String regionId) => switch (regionId) {
        'hokkaido' => (
            'Hokkaido miso ramen',
            'Rich amber miso broth, golden sweet corn kernels, pat of butter melting on surface, '
                'thick wavy noodles, chashu pork slices, spring onions, served in a wide white bowl with blue rim.',
          ),
        'kanto' => (
            'Tokyo shoyu ramen',
            'Clear deep-amber soy sauce broth, thin straight noodles, rolled chashu pork, '
                'halved soft-boiled egg showing orange yolk, sheet of nori, bamboo shoots, spring onions.',
          ),
        'kansai' => (
            'Osaka shio ramen',
            'Crystal-clear pale golden salt broth, thin noodles, white poached chicken slices, '
                'delicate yuzu zest garnish, thin spring onion rings, elegant minimalist presentation.',
          ),
        _ => (
            'Fukuoka tonkotsu ramen',
            'Opaque creamy white pork-bone broth, ultra-thin straight noodles, '
                'pink chashu pork, halved soft egg, red pickled ginger, black garlic oil drizzle, sesame seeds.',
          ),
      };

  String _shopDesc(String regionId) => switch (regionId) {
        'hokkaido' =>
          'Cosy rustic Hokkaido ramen shop interior. Warm wooden beams and worn timber counter, '
              'snowflakes visible through a frosted window, orange paper lanterns glowing overhead, '
              'four counter seats, giant steaming stockpot behind the pass.',
        'kanto' =>
          'Modern Tokyo ramen bar. Clean concrete-and-timber interior, bright pendant lighting, '
              'a long sleek counter with eight stools, subtle neon accent strips, open kitchen visible in back.',
        'kansai' =>
          'Elegant Osaka ramen restaurant. Light natural wood panelling, zen-minimal layout, '
              'soft diffused ambient lighting, low counter with wooden stools, small potted plants, serene and airy.',
        _ =>
          'Authentic Fukuoka ramen yatai stall at night. Rustic worn-timber counter open on three sides, '
              'warm glowing paper lanterns, dark night sky beyond, billowing steam from large pots, three bar stools.',
      };

  Future<Uint8List?> _generate(String key, String prompt) async {
    if (_cache.containsKey(key)) return _cache[key];
    if (_apiKey.isEmpty) {
      _log.logError('GameAsset', '_generate', 'No GEMINI_API_KEY');
      return null;
    }

    try {
      final url = '$_baseUrl/models/$_model:generateContent?key=$_apiKey';
      final response = await http.post(
        Uri.parse(url),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [
            {
              'parts': [
                {'text': prompt},
              ],
            },
          ],
          'generationConfig': {
            'responseModalities': ['TEXT', 'IMAGE'],
          },
        }),
      );

      if (response.statusCode != 200) {
        _log.logError('GameAsset', key, 'HTTP ${response.statusCode}');
        return null;
      }

      final bytes = _extractImageBytes(response.body);
      if (bytes != null) {
        _cache[key] = bytes;
        _log.logSuccess('GameAsset', key, '${bytes.length} bytes cached');
      }
      return bytes;
    } catch (e) {
      _log.logError('GameAsset', key, '$e');
      return null;
    }
  }

  Uint8List? _extractImageBytes(String body) {
    try {
      final data = jsonDecode(body) as Map<String, dynamic>;
      final candidates = data['candidates'] as List?;
      if (candidates == null || candidates.isEmpty) return null;
      final content = candidates[0]['content'] as Map<String, dynamic>?;
      final parts = content?['parts'] as List?;
      if (parts == null) return null;
      for (final part in parts) {
        if (part is Map && part.containsKey('inlineData')) {
          final b64 = (part['inlineData'] as Map)['data'] as String?;
          if (b64 != null) return base64Decode(b64);
        }
      }
      return null;
    } catch (e) {
      _log.logError('GameAsset', 'extractImageBytes', '$e');
      return null;
    }
  }
}

/// Sous chef expression states.
enum SousChefMood { neutral, excited, thinking }

/// Customer visual states.
enum CustomerState { waiting, served, unhappy }
