import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

import '../game/gourmet_go_game.dart';
import '../services/debug_logger.dart';
import '../services/ftue_service.dart';
import '../services/game_asset_service.dart';
import '../services/game_audio_service.dart';

/// FTUE sous-chef dialogue overlay — visual novel style.
///
/// Full-screen Flutter overlay with:
/// 1. Intro video (ftue_intro.mp4) plays first
/// 2. Kitchen background with animated darkness fade
/// 3. Large sous chef portrait (visual novel position)
/// 4. Dialogue box with tap-to-advance + pre-baked TTS audio
///
/// Dialogue script matches restaurant_sim_prototype.md §4 FTUE Script exactly.
/// Audio files generated by [generate_ftue_dialogue_audio.sh].
class FtueDialogueOverlay extends StatefulWidget {
  const FtueDialogueOverlay({required this.game, super.key});

  final GourmetGoGame game;

  @override
  State<FtueDialogueOverlay> createState() => _FtueDialogueOverlayState();
}

class _FtueDialogueOverlayState extends State<FtueDialogueOverlay>
    with SingleTickerProviderStateMixin {
  static final _log = DebugLogger.instance;
  static final _audio = GameAudioService();

  // ── State ──
  bool _showingIntroVideo = true;
  int _lineIndex = 0;
  bool _speaking = false;
  double _darknessOpacity = 0.85;

  // ── Video ──
  VideoPlayerController? _videoController;
  bool _videoReady = false;
  bool _videoError = false;

  /// Dialogue script — matches restaurant_sim_prototype.md §4 FTUE Script.
  ///
  /// Each line has:
  /// - `text`: the exact dialogue text from the spec
  /// - `mood`: sous chef portrait expression
  /// - `audioFile`: pre-baked TTS audio asset name
  /// - `darkness`: kitchen overlay opacity (fades as story progresses)
  /// - `section`: section header shown above dialogue for pacing
  static const _lines = [
    // ── Opening Story ──
    _Line(
      'Welcome, traveler.',
      SousChefMood.neutral,
      audioFile: 'ftue_line_01.mp3',
      darkness: 0.85,
      section: 'Opening Story',
    ),
    _Line(
      'This little ramen shop may look ordinary, but it carries a long, '
      'quiet history. Generations have stood behind this counter, tasting '
      'broth, perfecting noodles, and warming the souls of strangers far '
      'from home.',
      SousChefMood.thinking,
      audioFile: 'ftue_line_02.mp3',
      darkness: 0.75,
    ),
    _Line(
      'Now the shop is yours. You\'ve come from far away, carrying your '
      'own memories and flavors, and a promise to yourself: you\'ll not '
      'only keep this place alive, you\'ll make it more beloved than ever.',
      SousChefMood.neutral,
      audioFile: 'ftue_line_03.mp3',
      darkness: 0.6,
    ),
    _Line(
      'People from all over the world should feel at home here — no '
      'matter where they started their journey.',
      SousChefMood.excited,
      audioFile: 'ftue_line_04.mp3',
      darkness: 0.45,
    ),

    // ── Motivation to Travel and Discover ──
    _Line(
      'To do that, you can\'t stay in one place. Japan\'s ramen isn\'t '
      'just one bowl — it changes from town to town, coast to coast.',
      SousChefMood.thinking,
      audioFile: 'ftue_line_05.mp3',
      darkness: 0.35,
      section: 'The Journey Ahead',
    ),
    _Line(
      'If we want this shop to become a legend, we\'ll have to travel. '
      'From snowy northern ports to neon-lined streets, from quiet '
      'countryside stations to busy market alleys — every region has '
      'its own secrets in the broth.',
      SousChefMood.excited,
      audioFile: 'ftue_line_06.mp3',
      darkness: 0.2,
    ),

    // ── Tutorial: First Recipe ──
    _Line(
      'Every great journey starts with a single bowl.',
      SousChefMood.neutral,
      audioFile: 'ftue_line_07.mp3',
      darkness: 0.1,
      section: 'Your First Bowl',
    ),
    _Line(
      'First, let\'s add your very first ramen to the menu. Take a '
      'photo of a bowl you\'re eating right now — or upload one of '
      'your favorites.',
      SousChefMood.excited,
      audioFile: 'ftue_line_08.mp3',
      darkness: 0.0,
    ),
    _Line(
      'I\'ll bring that photo into the kitchen, and we\'ll study it together.',
      SousChefMood.excited,
      audioFile: 'ftue_line_09.mp3',
      darkness: 0.0,
    ),
  ];

  @override
  void initState() {
    super.initState();
    FtueService.instance.saveStep(FtueStep.intro);
    _initVideo();
  }

  void _initVideo() {
    try {
      _videoController = VideoPlayerController.asset(
        'assets/videos/ftue_intro.mp4',
      )
        ..setLooping(false)
        ..initialize().then((_) {
          if (mounted) {
            setState(() => _videoReady = true);
            _videoController!.play();
            _videoController!.addListener(_onVideoProgress);
          }
        }).catchError((Object e) {
          _log.logError('FtueDialogue', 'video init', '$e');
          if (mounted) {
            setState(() {
              _videoError = true;
              _showingIntroVideo = false;
            });
            _startDialogue();
          }
        });
    } catch (e) {
      _log.logError('FtueDialogue', 'video create', '$e');
      setState(() {
        _videoError = true;
        _showingIntroVideo = false;
      });
      _startDialogue();
    }
  }

  void _onVideoProgress() {
    final ctrl = _videoController;
    if (ctrl == null) return;
    if (ctrl.value.position >= ctrl.value.duration &&
        ctrl.value.duration > Duration.zero) {
      _skipVideo();
    }
  }

  void _skipVideo() {
    if (!_showingIntroVideo) return;
    _videoController?.removeListener(_onVideoProgress);
    _videoController?.pause();
    setState(() => _showingIntroVideo = false);
    _startDialogue();
  }

  void _startDialogue() {
    _audio.playFtueIntroMusic();
    _playCurrentLine();
  }

  void _playCurrentLine() async {
    if (_lineIndex >= _lines.length) return;

    final line = _lines[_lineIndex];
    setState(() {
      _speaking = true;
      _darknessOpacity = line.darkness;
    });

    // Play pre-baked TTS audio asset (no CORS issues, no API call needed).
    // Falls back to runtime TTS if asset fails.
    await _audio.speakLine(line.text);
    if (mounted) setState(() => _speaking = false);
  }

  void _advance() {
    if (_showingIntroVideo) {
      _skipVideo();
      return;
    }

    if (_speaking) {
      _audio.stopVoice();
      setState(() => _speaking = false);
      return;
    }

    if (_lineIndex < _lines.length - 1) {
      setState(() => _lineIndex++);
      _playCurrentLine();
    } else {
      // End of dialogue — transition to camera
      _log.logInfo('FtueDialogue', 'Dialogue complete, opening camera');
      FtueService.instance.saveStep(FtueStep.camera);
      widget.game.hideOverlay(GameOverlay.ftue);
      widget.game.showOverlay(GameOverlay.camera);
    }
  }

  @override
  void dispose() {
    _videoController?.removeListener(_onVideoProgress);
    _videoController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_showingIntroVideo) return _buildVideoScreen();
    return _buildDialogueScreen();
  }

  // ── Intro Video Screen ──

  Widget _buildVideoScreen() {
    return GestureDetector(
      onTap: _skipVideo,
      child: Container(
        color: Colors.black,
        child: Stack(
          fit: StackFit.expand,
          children: [
            if (_videoReady && _videoController != null)
              Center(
                child: AspectRatio(
                  aspectRatio: _videoController!.value.aspectRatio,
                  child: VideoPlayer(_videoController!),
                ),
              )
            else if (!_videoError)
              const Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text('🍜', style: TextStyle(fontSize: 48)),
                    SizedBox(height: 16),
                    CircularProgressIndicator(color: Colors.deepOrange),
                  ],
                ),
              ),

            // Skip button
            Positioned(
              right: 16,
              bottom: 40,
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                decoration: BoxDecoration(
                  color: Colors.black54,
                  borderRadius: BorderRadius.circular(20),
                ),
                child: const Text(
                  'Tap to skip ▶',
                  style: TextStyle(color: Colors.white60, fontSize: 14),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Visual Novel Dialogue Screen ──

  Widget _buildDialogueScreen() {
    final line = _lineIndex < _lines.length ? _lines[_lineIndex] : null;
    final mood = line?.mood ?? SousChefMood.neutral;

    return GestureDetector(
      onTap: _advance,
      behavior: HitTestBehavior.translucent,
      child: Stack(
        fit: StackFit.expand,
        children: [
          // ── Layer 1: Kitchen background ──
          Image.asset(
            'assets/sprites/kitchen_bg.png',
            fit: BoxFit.cover,
            errorBuilder: (_, __, ___) => Container(
              decoration: const BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Color(0xFF1A0A05),
                    Color(0xFF2D1508),
                    Color(0xFF1A0A05),
                  ],
                ),
              ),
            ),
          ),

          // ── Layer 2: Darkness overlay (fades during dialogue) ──
          AnimatedContainer(
            duration: const Duration(milliseconds: 1500),
            curve: Curves.easeInOut,
            color: Color.fromRGBO(0, 0, 0, _darknessOpacity),
          ),

          // ── Layer 3: Sous chef portrait (visual novel position) ──
          Positioned(
            bottom: 200,
            left: 0,
            right: 0,
            child: Center(
              child: AnimatedSwitcher(
                duration: const Duration(milliseconds: 300),
                child: Image.asset(
                  'assets/${GameAssetService.sousChefPortrait(mood)}',
                  key: ValueKey(mood),
                  height: 320,
                  fit: BoxFit.contain,
                  errorBuilder: (_, __, ___) => const SizedBox(
                    height: 320,
                    child: Center(
                      child: Text('🧑‍🍳', style: TextStyle(fontSize: 120)),
                    ),
                  ),
                ),
              ),
            ),
          ),

          // ── Layer 4: Section header (fades in with new sections) ──
          if (line?.section != null)
            Positioned(
              top: 60,
              left: 0,
              right: 0,
              child: Center(
                child: Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 20,
                    vertical: 8,
                  ),
                  decoration: BoxDecoration(
                    color: Colors.black54,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                      color: Colors.deepOrange.withAlpha(60),
                    ),
                  ),
                  child: Text(
                    line!.section!,
                    style: const TextStyle(
                      color: Colors.deepOrange,
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.5,
                    ),
                  ),
                ),
              ),
            ),

          // ── Layer 5: Dialogue box (visual novel style - bottom) ──
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            child: Container(
              margin: const EdgeInsets.all(12),
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: const Color(0xE6101020),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(
                  color: Colors.deepOrange.withAlpha(120),
                  width: 2,
                ),
                boxShadow: [
                  BoxShadow(
                    color: Colors.deepOrange.withAlpha(30),
                    blurRadius: 20,
                    spreadRadius: 2,
                  ),
                ],
              ),
              child: SafeArea(
                top: false,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Chef name badge
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 12,
                        vertical: 4,
                      ),
                      decoration: BoxDecoration(
                        color: Colors.deepOrange.withAlpha(60),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Text(
                            'The Master',
                            style: TextStyle(
                              color: Colors.deepOrange,
                              fontSize: 14,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          const SizedBox(width: 6),
                          if (_speaking)
                            const _SpeakingIndicator()
                          else
                            const Text(
                              '🍜',
                              style: TextStyle(fontSize: 14),
                            ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 12),

                    // Dialogue text
                    Text(
                      line?.text ?? '',
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 17,
                        height: 1.6,
                        letterSpacing: 0.3,
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Tap indicator + progress
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        // Progress dots
                        Row(
                          children: List.generate(
                            _lines.length,
                            (i) => Container(
                              width: 8,
                              height: 8,
                              margin: const EdgeInsets.only(right: 4),
                              decoration: BoxDecoration(
                                shape: BoxShape.circle,
                                color: i <= _lineIndex
                                    ? Colors.deepOrange
                                    : Colors.white24,
                              ),
                            ),
                          ),
                        ),
                        Text(
                          _speaking ? '⏸ tap to skip' : '▶ tap to continue',
                          style: const TextStyle(
                            color: Colors.white38,
                            fontSize: 12,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// Animated speaking indicator (bouncing dots).
class _SpeakingIndicator extends StatefulWidget {
  const _SpeakingIndicator();

  @override
  State<_SpeakingIndicator> createState() => _SpeakingIndicatorState();
}

class _SpeakingIndicatorState extends State<_SpeakingIndicator>
    with SingleTickerProviderStateMixin {
  late AnimationController _anim;

  @override
  void initState() {
    super.initState();
    _anim = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 600),
    )..repeat(reverse: true);
  }

  @override
  void dispose() {
    _anim.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _anim,
      builder: (context, child) {
        return Row(
          mainAxisSize: MainAxisSize.min,
          children: List.generate(3, (i) {
            final delay = i * 0.2;
            final t = ((_anim.value + delay) % 1.0);
            return Container(
              width: 5,
              height: 5,
              margin: const EdgeInsets.symmetric(horizontal: 1),
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: Colors.deepOrange.withAlpha((100 + 155 * t).toInt()),
              ),
            );
          }),
        );
      },
    );
  }
}

/// Dialogue line with mood, audio file, and darkness level.
class _Line {
  const _Line(
    this.text,
    this.mood, {
    required this.audioFile,
    this.darkness = 0.5,
    this.section,
  });

  final String text;
  final SousChefMood mood;
  final String audioFile;
  final double darkness;
  final String? section;
}
